# Generated by Django 5.0.2 on 2024-03-03 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('wins', models.IntegerField()),
                ('podiums', models.IntegerField()),
                ('wdc', models.IntegerField()),
                ('team_principal', models.TextField()),
                ('drivers', models.TextField()),
            ],
        ),
    ]
