# Generated by Django 5.0.2 on 2024-03-03 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='drivers',
        ),
        migrations.RemoveField(
            model_name='team',
            name='team_principal',
        ),
    ]
