# Generated by Django 5.0.2 on 2024-03-03 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_remove_team_drivers_remove_team_team_principal'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='car',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='team',
            name='engine',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='team',
            name='factory_base',
            field=models.TextField(blank=True),
        ),
    ]
