# Generated by Django 5.0.2 on 2024-03-03 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0002_alter_person_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='nationality',
            new_name='country',
        ),
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.URLField(blank=True),
        ),
    ]
